# Generated by Django 5.2.1 on 2026-05-29 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP Fuel/Procurement'), ('utility', 'Utility Electricity'), ('travel', 'Corporate Travel')], max_length=20)),
                ('source_file', models.CharField(blank=True, max_length=500)),
                ('source_row', models.IntegerField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited_at', models.DateTimeField(blank=True, null=True)),
                ('edited_by', models.CharField(blank=True, max_length=100)),
                ('scope', models.CharField(choices=[('scope1', 'Scope 1 - Direct'), ('scope2', 'Scope 2 - Indirect Electricity'), ('scope3', 'Scope 3 - Value Chain')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('raw_value', models.FloatField()),
                ('raw_unit', models.CharField(max_length=50)),
                ('normalized_value_kg_co2e', models.FloatField(blank=True, null=True)),
                ('activity_period_start', models.DateField(blank=True, null=True)),
                ('activity_period_end', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspicious', 'Flagged Suspicious')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('flag_reason', models.CharField(blank=True, max_length=500)),
                ('locked_for_audit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='companies.company')),
            ],
            options={
                'ordering': ['-ingested_at'],
            },
        ),
    ]
